# https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/creating-a-github-pages-site-with-jekyll?platform=linux
# https://pages.github.com/versions/

site: Interra Project
domain: Interra-Project.github.io

url: https://interra-project.org
baseurl: 

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /papers/:slug
    type: "post"

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post" 

sass:
  sass_dir: assets/styles
  style: compressed
  sourcemap: never

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-seo-tag

paginate: 6
paginate_path: "/papers/page:num/"
  
